{
  description = "A PHP framework for data-as-a-service agent projects";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    utils.url = "github:numtide/flake-utils";
    ema.url = "github:judijasa/ema";
  };

  outputs = { self, nixpkgs, utils, ema }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        phpPkg = pkgs.php84.withExtensions ({ all, enabled }:
          enabled ++ [
            all.mysqli
            all.pdo_mysql
            all.bz2  # required by jakoch/phantomjs-installer (composer)
          ]
        );
        # Make sure Composer uses this php, as it has the required extensions.
        phpComposer = pkgs.php84Packages.composer.override {
          php = phpPkg;
        };
        emaPkg = ema.packages.${system}.default;
      in
      {
        # PRODUCTION ARTIFACT: the phprun CLI + runner, the deploy CLI, the
        # gen-env/cron-manifest deploy helpers, and the dev-init machinery
        # (init-local-env.sh, init-cluster.sh, shell-enter.sh), for flakes
        # (e.g. added to a caller's commonPackages). The dev scripts are
        # fully parameterized / CWD-relative, so consumers call them from
        # their own dev-init chain and keep their consumer-specific steps
        # (git hooks, hosts, etc.) in their own Makefile.
        packages.default = pkgs.runCommand "php-daas-framework" { } ''
          mkdir -p $out/bin
          cp ${./bin/phprun} $out/bin/phprun
          chmod +x $out/bin/phprun
          cp ${./bin/deploy} $out/bin/deploy
          chmod +x $out/bin/deploy
          cp ${./bin/gen-env} $out/bin/gen-env
          chmod +x $out/bin/gen-env
          cp ${./bin/cron-manifest} $out/bin/cron-manifest
          chmod +x $out/bin/cron-manifest
          cp ${./bin/dev/init-local-env.sh} $out/bin/init-local-env.sh
          chmod +x $out/bin/init-local-env.sh
          cp ${./bin/dev/init-cluster.sh} $out/bin/init-cluster.sh
          chmod +x $out/bin/init-cluster.sh
          cp ${./bin/dev/shell-enter.sh} $out/bin/shell-enter.sh
          chmod +x $out/bin/shell-enter.sh
          cp -r ${./src} $out/src
        '';

        # DEVELOPMENT ENVIRONMENT: PHP + composer + ema + local MariaDB, for
        # template usage and the quick DB integration test (see README).
        devShells.default = pkgs.mkShell {
          buildInputs = [
            pkgs.bash
            phpPkg
            phpComposer
            emaPkg
            pkgs.jq      # used by `ema init tables`
            pkgs.mariadb_118
          ];
          shellHook = ''
            # .env is the single machine settings file (git-ignored),
            # generated by `make dev-init` (bin/dev/init-local-env.sh): it
            # carries the runtime config (REPO_PATH, REPO_LOG, REUTER_INI,
            # EMA_TARGET, DBUSER) and the derived paths (MYSQL_*). Nothing
            # is exported here anymore: the shell only sources .env and
            # resumes the local MariaDB daemon (shell-enter.sh) - without
            # .env there is no data dir, so MariaDB cannot be started.
            . ./bin/dev/shell-enter.sh

            # Customize the prompt (PS1)
            CYAN='\033[0;36m'
            GREEN='\033[0;32m'
            NC='\033[0m'
            export PS1="\[$CYAN\] \u@\h:\[$GREEN\]\w\[$NC\]\$ "
          '';
        };
      }
    );
}
